[workspace]
resolver = "2"
members = [
    "bin",
    "lib",
    "gui",
]

default-members = [
    "bin",
    "lib",
    "gui",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
gdal = { version = "0.19.0", features = ["bindgen"] }
